/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifsul.passofundo.projetolpooe1_leopoldonetorodrigues.view;

import br.edu.ifsul.passofundo.projetolpooe1_leopoldonetorodrigues.dao.PersistenciaJPA;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Passagem;

/**
 *
 * @author leo
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        carregarHistorico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuCad = new javax.swing.JMenu();
        ItemFunc = new javax.swing.JMenuItem();
        ItemMotorista = new javax.swing.JMenuItem();
        ItemVei = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuPedagio = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MenuSobre = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Motorista", "Veículo", "Data"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Histórico");

        MenuCad.setText("Cadastros");

        ItemFunc.setText("Funcionário");
        ItemFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemFuncActionPerformed(evt);
            }
        });
        MenuCad.add(ItemFunc);

        ItemMotorista.setText("Motorista");
        ItemMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemMotoristaActionPerformed(evt);
            }
        });
        MenuCad.add(ItemMotorista);

        ItemVei.setText("Veículo");
        ItemVei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemVeiActionPerformed(evt);
            }
        });
        MenuCad.add(ItemVei);

        jMenuBar1.add(MenuCad);

        jMenu2.setText("Pedágio");

        MenuPedagio.setText("Adicionar registro");
        MenuPedagio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPedagioActionPerformed(evt);
            }
        });
        jMenu2.add(MenuPedagio);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ajuda");

        MenuSobre.setText("Sobre");
        MenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSobreActionPerformed(evt);
            }
        });
        jMenu3.add(MenuSobre);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSobreActionPerformed
        TelaSobre telaSobre = new TelaSobre(this, rootPaneCheckingEnabled);
        telaSobre.setVisible(true);
    }//GEN-LAST:event_MenuSobreActionPerformed

    private void MenuPedagioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPedagioActionPerformed
        TelaPedagio telaPedagio = new TelaPedagio(this, rootPaneCheckingEnabled);
        telaPedagio.setVisible(true);
    }//GEN-LAST:event_MenuPedagioActionPerformed

    private void ItemFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemFuncActionPerformed
        TelaFunc telaFunc = new TelaFunc();
        telaFunc.setVisible(true);
    }//GEN-LAST:event_ItemFuncActionPerformed

    private void ItemMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemMotoristaActionPerformed
        TelaMotorista telaMotorista = new TelaMotorista();
        telaMotorista.setVisible(true);
    }//GEN-LAST:event_ItemMotoristaActionPerformed

    private void ItemVeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemVeiActionPerformed
        TelaVei telaVei = new TelaVei();
        telaVei.setVisible(true);
    }//GEN-LAST:event_ItemVeiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    
    public void carregarHistorico() {
        PersistenciaJPA jpa = new PersistenciaJPA(); // Criação da instância do JPA
        List<Passagem> movimentacoes = jpa.getMovimentacoes(); // Recupera as passagens do banco de dados

        // Cria o modelo da tabela com as colunas apropriadas
        DefaultTableModel model = new DefaultTableModel(
            new Object[][]{}, // Inicializa a tabela sem dados
            new String[]{"Motorista", "Veículo", "Data"} // Definição das colunas
        );

        // Preenche a tabela com os dados das passagens
        for (Passagem passagem : movimentacoes) {
            Object[] row = new Object[3];
            row[0] = passagem.getMotorista().getNome(); // Nome do motorista
            row[1] = passagem.getVeiculo().getPlaca(); // Modelo do veículo
            row[2] = passagem.getDataHora().toString(); // Data e hora da passagem
            model.addRow(row); // Adiciona a linha na tabela
        }

        // Define o modelo para a tabela
        jTable1.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemFunc;
    private javax.swing.JMenuItem ItemMotorista;
    private javax.swing.JMenuItem ItemVei;
    private javax.swing.JMenu MenuCad;
    private javax.swing.JMenuItem MenuPedagio;
    private javax.swing.JMenuItem MenuSobre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
