/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifsul.passofundo.projetolpooe1_leopoldonetorodrigues.view;

import br.edu.ifsul.passofundo.projetolpooe1_leopoldonetorodrigues.dao.PersistenciaJPA;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import model.Veiculo;
import model.Tipo;
/**
 *
 * @author leo
 */
public class TelaVei extends javax.swing.JFrame {
    
    PersistenciaJPA jpa = new PersistenciaJPA();
    
    /**
     * Creates new form TelaFunc
     */
    public TelaVei() {
        initComponents();
        loadVeiculosCadastrados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddVeiculo = new javax.swing.JButton();
        btnEditarVeiculo = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVeiculos = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAddVeiculo.setText("Novo");
        btnAddVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVeiculoActionPerformed(evt);
            }
        });

        btnEditarVeiculo.setText("Editar");
        btnEditarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarVeiculoActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        tblVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Placa", "Tipo", "Marca", "Descricao", "Cor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblVeiculos);

        lblTitulo.setText("Veiculos");

        jLabel2.setText("Placa:");

        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });
        txtPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPlacaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnAddVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnEditarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPlaca))
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddVeiculo)
                    .addComponent(btnEditarVeiculo)
                    .addComponent(btnRemover))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVeiculoActionPerformed
        TelaCadVei tela = new TelaCadVei(this, rootPaneCheckingEnabled);
        tela.setVisible(true);

        loadVeiculosCadastrados();
    }//GEN-LAST:event_btnAddVeiculoActionPerformed

    private void btnEditarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarVeiculoActionPerformed

        Veiculo veiculoSel = getVeiculoSelecionado();
        if (veiculoSel != null) {
            TelaCadVei tela = new TelaCadVei(this, rootPaneCheckingEnabled);
            tela.setVeiculo(veiculoSel); 
            tela.setVisible(true);
            loadVeiculosCadastrados(); 
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um veículo para editar.");
        }
    }//GEN-LAST:event_btnEditarVeiculoActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        Veiculo veiculoSel = getVeiculoSelecionado(); // Obter o veículo selecionado
        if (veiculoSel != null) { // Se um veículo foi selecionado
            int confirm = JOptionPane.showConfirmDialog(
                this,
                "Tem certeza que deseja remover o veículo com placa " + veiculoSel.getPlaca() + "?",
                "Confirmar Remoção",
                JOptionPane.YES_NO_OPTION
            );

            if (confirm == JOptionPane.YES_OPTION) { // Se o usuário confirmou a remoção
                try {
                    jpa.conexaoAberta(); // Abre a conexão
                    jpa.remover(veiculoSel); // Remove o veículo do banco
                    jpa.fecharConexao(); // Fecha a conexão
                    JOptionPane.showMessageDialog(this, "Veículo removido com sucesso!");
                    loadVeiculosCadastrados(); // Atualiza a tabela
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Erro ao remover veículo: " + e.getMessage());
                    e.printStackTrace();
                } finally {
                    jpa.fecharConexao(); // Garante que a conexão será fechada
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um veículo para remover.");
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void txtPlacaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacaKeyReleased
        String texto = txtPlaca.getText().toLowerCase();
        if (!texto.isEmpty()) {  
            try {
                List<Veiculo> resultados = jpa.getVeiculosByPlaca(texto);
                DefaultTableModel model = (DefaultTableModel) tblVeiculos.getModel();  
                model.setRowCount(0);  

               
                for (Veiculo veiculo : resultados) {
                    model.addRow(new Object[]{
                        veiculo.getPlaca(),
                        veiculo.getCor(),
                        veiculo.getTipo(),
                        veiculo.getMarca(),
                        veiculo.getDescricao(),
                    });
                }
            } catch (Exception e) {
                Logger.getLogger(TelaVei.class.getName()).log(Level.SEVERE, null, e);
            }
        } else {
            // Se o campo estiver vazio, você pode limpar a tabela ou mostrar todos os veículos
            loadVeiculosCadastrados();
        }
    }//GEN-LAST:event_txtPlacaKeyReleased

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVei.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVei.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVei.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVei.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVei().setVisible(true);
            }
        });
    }
    
    public void loadVeiculosCadastrados() {
        jpa.conexaoAberta();
        try {
            List<Veiculo> listaVeiculos = jpa.getVeiculos(); 

            DefaultTableModel modeloTabela = (DefaultTableModel) tblVeiculos.getModel();

            modeloTabela.setRowCount(0);

            for (Veiculo veiculo : listaVeiculos) {
                Object[] linha = {
                    veiculo.getPlaca(),
                    veiculo.getTipo(),
                    veiculo.getMarca(),
                    veiculo.getDescricao(),
                    veiculo.getCor()
                };
                modeloTabela.addRow(linha);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao carregar os veículos: " + e.getMessage());
        } finally {
            jpa.fecharConexao();
        }
}

    public Veiculo getVeiculoSelecionado() {
        int linhaSelecionada = tblVeiculos.getSelectedRow(); // Obtém a linha selecionada
        if (linhaSelecionada >= 0) {
            DefaultTableModel modeloTabela = (DefaultTableModel) tblVeiculos.getModel();

            // Recupera a placa da coluna 0
            String placaSelecionada = (String) modeloTabela.getValueAt(linhaSelecionada, 0);

            try {
                // Busca o veículo no banco usando a placa
                Veiculo veiculoSelecionado = jpa.getVeiculoByPlaca(placaSelecionada);
                if (veiculoSelecionado == null) {
                    JOptionPane.showMessageDialog(this, "Veículo não encontrado no banco de dados.");
                }
                return veiculoSelecionado;
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao buscar o veículo: " + e.getMessage());
                e.printStackTrace();
                return null;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nenhuma linha selecionada.");
            return null;
        }
    }





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddVeiculo;
    private javax.swing.JButton btnEditarVeiculo;
    private javax.swing.JButton btnRemover;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblVeiculos;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
